### ISSUE TITLE
Multiple DB connection pools initialized

### ISSUE THREAD

**Issue by cwei-bgl** [dnvriend/akka-persistence-jdbc#101]
Hi,

Thanks for the library. I am currently profiling my application. I noticed there was a strange behaviour with akka-peristence-jdbc. I am using HikariDataSource. The library is trying to create new DB pool in following cases:
1. JdbcReadJournal will have a new DB pool. I checked the source code in akka.persistence.jdbc.query.scaladsl.JdbcReadJournal
2. A persistent actor will create two DB pools. I saw logs from console.
`
2017-05-11 16:25:37,939 INFO  [undefined] com.zaxxer.hikari.HikariDataSource.<init>(70)  - slick.db - Started.
2017-05-11 16:25:37,940 WARN  [undefined] slick.basic.DatabaseConfig.warn(25)  - Use `slick.profile` instead of `slick.driver`. The latter is deprecated since Slick 3.2 and will be removed.
2017-05-11 16:25:37,947 INFO  [undefined] com.zaxxer.hikari.HikariDataSource.<init>(70)  - slick.db - Started.
2017-05-11 16:25:37,948 WARN  [undefined] slick.basic.DatabaseConfig.warn(25)  - Use `slick.profile` instead of `slick.driver`. The latter is deprecated since Slick 3.2 and will be removed.
`

The following picture was taken from VisualVM.
![image](https://cloud.githubusercontent.com/assets/12963397/25935827/4d7878ee-3668-11e7-9528-e38ad7a131b3.png)

Now I have four DB pools. Ideally, I only want one to be shared by all. Could you help me? 

Thanks,
Cheng

**Comment by dnvriend** [comment]
Hi, thanks for the info! I got to look into that. Its put on the backlog.

**Comment by cwei-bgl** [comment]
@dnvriend , Thanks Dennis. I wish this one can be a high priority, It consumes a lot of resources. Thanks.

**Comment by dnvriend** [comment]
@cwei-bgl The connector creates a new db pool per plugin. This is by design. With 'plugin' I mean: 'jdbc-journal', 'jdbc-snapshot-store', 'jdbc-read-journal'. The plugins only do this when enabled of course so eg. when you set in 'application.conf' the following

```
akka {
 persistence {
     journal.plugin = "jdbc-journal"
     snapshot-store.plugin = "jdbc-snapshot-store"
   }
}
``` 

This will cause two plugins to be started called 'jdbc-journal' and 'jdbc-snapshot-store' and you will have two db-connection pools. You can tweak the connection pool instances of the plugins via configuration (see reference.conf), in visualvm threads tab I see here you have a lot of threads that have been spawned by hikari. These settings can be tweaked per plugin so eg:

```

  slick.db.numThreads = 1
  slick.db.maxConnections = 1
  slick.db.minConnections = 1
  slick.db.connectionTimeout = 1800000 // 30 minutes

  recovery-event-timeout = 60m
}

Here we use only a single JDBC connection and spawn only one thread. Of course this impacts the performance of the plugin and also the concurrent behavior to the JDBC database. Tweak these values as per your use case. For an example how to tweak the plugins see [akka-persistence-jdbc-test](https://github.com/dnvriend/akka-persistence-jdbc-test) which is a very simple example.

**Comment by cwei-bgl** [comment]
@dnvriend , Appreciate your prompt reply, Dennis. Thanks for the detailed explanation. That makes sense. I now see the reason that I had four pools was that I used all the three plugins plus app itself using a DB pool. By the way, It looks to me that configuring jdbc-journal and jdbc-snapshot-store to be single threaded connection pool is valid for most normal use cases. As they are operating on a single table. Am I right?

**Comment by dnvriend** [comment]
@cwei-bgl You should measure the performance and tweak the plugin and your Timeouts as per NFR and SLA requirements for the environment you are running your solution in. But IMHO its a good place to start, and only ramp up the resources when you need to. With reactive applications you have several knobs to turn, but its good to start with a few threads and a few JDBC connections  and go from there. Monitor the JDBC load and your application and tweak them appropriately.

**Comment by cwei-bgl** [comment]
@dnvriend Thanks Dennis. close for now.
