### ISSUE TITLE
Support for MS-SQL-server

### ISSUE THREAD

**Issue by dnvriend** [dnvriend/akka-persistence-jdbc#102]

**Comment by naferx** [comment]
I would like to contribute with this

**Comment by dnvriend** [comment]
Any PR is welcome. There is a [mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/) docker image available.

**Comment by naferx** [comment]
I'll be pushing commits progressively

**Comment by WellingR** [comment]
Closing this as this has been implemented as part of #200. This feature is now available in akka-persistence-jdbc 3.5.0
