### ISSUE TITLE
JdbcReadJournal in javadsl does not support CurrentEventsByTagQuery2 and EventsByTagQuery2

### ISSUE THREAD

**Issue by ahogenboom** [dnvriend/akka-persistence-jdbc#106]
`CurrentEventsByTagQuery` and `EventsByTagQuery` are deprecated, so it is recommended to switch to `CurrentEventsByTagQuery2` and `EventsByTagQuery2` until Akka 2.5.0 renames the latter two to the former two.

There is support for `CurrentEventsByTagQuery2` and `EventsByTagQuery2` in `akka.persistence.jdbc.query.scaladsl.JdbcReadJournal`, but this is not the case for `akka.persistence.jdbc.query.javadsl.JdbcReadJournal`. Could this be added please? I'm not a Scala expert, but to me, it looks like only two lines need to be added to `akka.persistence.jdbc.query.javadsl.JdbcReadJournal` (line 35):
```
with CurrentEventsByTagQuery2
with EventsByTagQuery2
```
A new release for Akka 2.4.18 and up that includes this would be much appreciated!

**Comment by dnvriend** [comment]
You're absolutely right. I just released 2.4.18.2, that should include the missing Java API.

**Comment by ahogenboom** [comment]
Great, thank you so much for the quick update and release! Works like a charm now =)
