### ISSUE TITLE
Wrong parameters list in MS SQL Server statements

### ISSUE THREAD

**Issue by orsonek** [dnvriend/akka-persistence-jdbc#11]
In file journal/Statements.scala a parameter is missing for MS SQL Server (3 '?', expected 4). After correction some other exception are thrown and simple workaround (no binding) may be applied:

trait MSSqlServerStatements extends GenericStatements {
  override def selectMessagesFor(persistenceId: String, fromSequenceNr: Long, toSequenceNr: Long, max: Long): List[PersistentRepr] = {
    SQL(s"SELECT TOP $max message FROM $schema$table WHERE persistence_id = '$persistenceId' AND (sequence_number >= $fromSequenceNr AND sequence_number <= $toSequenceNr) ORDER BY sequence_number")
      //.bind(max, persistenceId, fromSequenceNr, toSequenceNr)
      .map(rs => Journal.fromBytes(Base64.decodeBinary(rs.string(1))))
      .list()
      .apply
  }
}

**Comment by dnvriend** [comment]
Please alter the source code and issue a pull request. It would be nice to have a MS SQL Server available as a docker image so I can test it..

**Comment by bpg** [comment]
Pull request #15 fixes this issue and couple of other SQL Server -specific minors. Works fine in my environment.
I'm planning to make an additional improvement there, similar to #13 -- to convert INSERT-fail-UPDATE logic into a stored procedure.
