### ISSUE TITLE
Using a Datasource to initialize akka-persistence-jdbc

### ISSUE THREAD

**Issue by mwkohout** [dnvriend/akka-persistence-jdbc#12]
I've got an application that is switching over to Oracle Wallet based authentication-this means that it will no longer use username and passwords but will use certificates instead.

Without hacking akka-persistence-jdbc, how can I override the database the code uses?

FYI, I'm using akka(2.3.5) and akka-persistence-jdbc(1.08) via Groovy and spring.

**Comment by dnvriend** [comment]
Hi

Thats a very good question :). Did not know of this authentication feature util now. AFAIK you can not with Oracle XE and scalikejdbc but maybe they both support it but i dont know how. did a Quick scan of the scalikejdbc site and searched Google. But if you do or feel up to it fork, alter the code and create a pull request So others can benefit.

regards

**Comment by mwkohout** [comment]
I'll likely try to submit a nice change but until then for for others who have this issue, I was able to make it work by
1.  forcing the ScalikeExtension to initialize in my code, setting up the bad datasource:             
      ScalikeExtension.get(system)
2.  And then override it with my own after:
     ConnectionPool.singleton(new DataSourceConnectionPool(jdbcDatsource))


Hopefully I can come up with an elegant fix.

**Comment by haywood** [comment]
+1

**Comment by cridmann** [comment]
+1, this would be a nice feature.  @mwkohout that should def seem to work in the interim - thanks

**Comment by dnvriend** [comment]
Release 1.1.1 will have initial support for JNDI, please test it, for I don't use app servers anymore... Play apps, what can I say :-)

**Comment by cridmann** [comment]
I just tested this using wso2-app-server (tomcat) and it worked.  Thanks dennis!

**Comment by dnvriend** [comment]
Thanks, no problem :-) Also thanks for testing!
