### ISSUE TITLE
CurrentEventsByTag potentially broken

### ISSUE THREAD

**Issue by rcavalcanti** [dnvriend/akka-persistence-jdbc#124]
`currentEventsByTag` is supposed to return a finite `Source` that starts from passed `Offset` up to last known event. When it finishes, it finishes and new events are not delivered. It's possible that such a query returns an empty `Source`. 

It relies on the `JournalSequenceActor` to determine what is the max known ordering, but just after starting, that actor considers that the max ordering is 0. It takes a while before it "learns" what is the real max ordering. During that period, `currentEventsByTag` will return an empty `Source` even if there are events starting from the passed offset.

This won't happen only at start up time. A system with a journal with tens of thousands events will also suffer from it. 

For instance, the default buffer size is 10000. For a journal with 100k events, a call to `currentEventsByTag` starting from offset 30000, will return an empty `Source` in the beginning. After some time, when the max ordering becomes, let's say 50000, it will return a `Source` from 30001 to 50000, while the correct one would have been 30001 to 100000.

**Comment by rcavalcanti** [comment]
Hi @WellingR, can we you have a look on this one? 

I believe we need to have `JournalSequenceActor` stabilising on startup before answering to any calls from outside. 

Once it knows what is the max ordering, it can start answering and keep tracking of gaps.

**Comment by WellingR** [comment]
I will have a look at this the coming weekend

**Comment by rcavalcanti** [comment]
I have been thinking on a solution for that and I got stuck with the following. 

## Scenario 1 - single node, single writer
When the plugin starts, it could first try to stabilise on the max ordering before becoming really available. That would solve the issue with `currentEventsByTag`. 

Once we stabilise, we start polling `QueryOrderingIds`. The purpose of the polling would be to detect gaps one the fly and it would always starts from the value return by `maxJournalSequence` on bootstrap. 

## Scenario 2 - many nodes, many writers

When used in a clustered environment, the following may happen: 
(only 2 nodes for the sake of simplicity)

1. at T0: node 1 is running and is stable. MaxOrdering is 100 and it keep using `QueryOrderingIds` to introduce delay
2. at T1: node 1 writes a couple of new events: 101, 102, 103, ~*104*~, 105  
(note that 104 is missing)
3. at T2: node 2 starts and queries the DB to learn what is the max, because it will immediately see 105, it will consider it as the maxOrdering
4. at T3: event 104 becomes visible in DB, node 1 detects it and set its' max to 104

### Consequences
Node 1 will be able to consume 104, but node 2 won't. If it happens that node 2 has a query that it's supposed to read event 104, it will miss it forever.

Not stabilising the maxOrdering on startup breaks `currentEventsByTag`, but stabilising it will break queries in clustered environments. We definitely need something else.

**Comment by rcavalcanti** [comment]
## Possible solution:

We could introduce a backtracking value. 

On startup, we determine the `maxOrdering` like explained before,
then
```
val startMaxOrdering = maxOrdering - backtracking
```

We start the polling with `QueryOrderingIds` using `startMaxOrdering`. This will give recently joining node the chance to detect gaps. 

The question is, what shall the default value be? 100, 1000, 10000? It all depends on the real load.

**Comment by WellingR** [comment]
Currently the journal sequence actor is started lazily, for the reason that the actor should not query the database continuously if the (current)EventsByTag query is never used at all.

This should actually mean that on startup, the eventsByTag query could indeed return an empty source, because the journal sequence actor was not completely ready yet.

You state a potential issue in scenario 2
> at T2: node 2 starts and queries the DB to learn what is the max, because it will immediately see 105, it will consider it as the maxOrdering

Actually this is not the case, it will query the max ordering and see 105, but it will use a delay after queryDelay * maxTries (which is 10 seconds by default). The journal sequence actor has been created to prevent this issue, the querying for the max ordering has been implemented to be able to recover very quickly to a high number.

The only assumption we need to make is that the 10 second period (queryDelay * maxTries) is sufficient to ensure that all running insertions on the database have completed.

### Proposed solution
If we truly want to return the events which are current at the moment of calling the currentEventsByTag query. Then we could do roughly the following (which should require no modifications to the journal sequence actor).

1. When the currentEventsByTag query is called we query the database for the current max ordering id. Call this value `until`
2. We run the regular eventsByTag query with a takewhile: `eventsByTag(tag, offset).takeWhile(_.offset.value <= until)`

I will see if I can create a PR with this solution this weekend

**Comment by rcavalcanti** [comment]
> Currently the journal sequence actor is started lazily, for the reason that the actor should not query the database continuously if the (current)EventsByTag query is never used at all.

I don't think this is a good idea. Consumption of events is a very common use case in event sourced application. Most of the times applications start to consume events as soon as they start. The sooner we get it "stabilized" the better.

The problem I described in scenario 2:T2 won't happen with the current impl, that's true, but my previous point was that we need some stabilisation mechanism. And we can't stabilise without going back in time. 
This is only valid for clustered env. With a single node, it's safe to assume that 105 is the last offset and that nothing will appear before it. 
This assumption is invalid when we have multiple writers. When node2 sees 105 after startup, it can't be sure that node1 has a running thread that will commit 104. 

About the new proposal...
> If we truly want to return the events which are current at the moment of calling the currentEventsByTag query. 
Yes, for sure. That's what the contract of the API. We can't return an empty Source here. 

I don't get the new proposal actually.
If we query for the current max and then keep asking the `JournalSequenceActor` for the max value we are actually asking it to catchup with the max value before returning a`Source`. Is that what you had in mind? 

If we fix the max jump (as explained in #126) than the will take at most 10 secs to stabilise. 
It's hard to come up with numbers, but huge journals will always take 10 secs to stabilise. Instead we could make the initial `currentMaxOrdering` configurable, defaulting to 0. 
If I know that offset 3000 is safe, for instance, I could configure my system to seek the max starting from 3000 instead of 0.

**Comment by WellingR** [comment]
> Currently the journal sequence actor is started lazily...

> I don't think this is a good idea. Consumption of events is a very common use case in event sourced application. Most of the times applications start to consume events as soon as they start. The sooner we get it "stabilized" the better.

What we could do is make the eager/configurable starting of the journal sequence actor. Perhaps starting eagerly could become the default.

> I don't get the new proposal actually.
If we query for the current max and then keep asking the `JournalSequenceActor` for the max value we are actually asking it to catchup with the max value before returning a`Source`. Is that what you had in mind?

That is correct.

> It's hard to come up with numbers, but huge journals will always take 10 secs to stabilise. Instead we could make the initial `currentMaxOrdering` configurable, defaulting to 0.

I agree that it could be a good thing to make this configurable.
