### ISSUE TITLE
Journal Table Schema Discrepancy

### ISSUE THREAD

**Issue by acchaulk** [dnvriend/akka-persistence-jdbc#130]
There is a discrepancy between the [databases schemas](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/schema/postgres/postgres-schema.sql#L10) and the [JournalTables schema](https://github.com/dnvriend/akka-persistence-jdbc/blob/69086811a20f6571c3a178ceff67323381a3fae0/src/main/scala/akka/persistence/jdbc/journal/dao/JournalTables.scala#L38). 
I noticed slower query performance for the query:
```
select "sequence_number" from "journal" where "persistence_id" = ? order by "sequence_number" desc limit ?
```

The schemas in the test package seem to optimize for that query better that the JournalTables.scala schema due to a separate index on "ordering". What is the reason for this difference?

**Comment by WellingR** [comment]
Thanks for spotting this! The schemas in the test package (which are also the ones we link to from the readme) are indeed the ones that should be used.

I guess the reason for this discrepancy is just some legacy. Our own code is dependent on the JournalTables only for executing queries, not for generating the DDL. But I agree that this should be corrected.

I will merge your PR soon

**Comment by WellingR** [comment]
#132 has been merged
