### ISSUE TITLE
Question: is there any example in java?

### ISSUE THREAD

**Issue by bodrin** [dnvriend/akka-persistence-jdbc#156]
Hi,
I would like to try java+akka+persistence+postgreSQL and found this plugin.
Is there any chance you will provide a java example into the future or are you aware if there already exist some?
Thanks!

**Comment by WellingR** [comment]
When you have configured this plugin (our readme contains the info how to do this, this is the same for java and scala), you do not actually interact with this plugin directly.

The akka documentation contains lots of examples for akka-persistence in both java and scala: See
https://doc.akka.io/docs/akka/2.5.4/java/persistence.html

**Comment by bodrin** [comment]
Hi WellingR,
Thanks for the explanation!
I'll try to consume this plugin in an example java akka project. I will report back here so for now I guess that the issue can be closed.
Thanks!
