### ISSUE TITLE
Build with scalikejdbc-2.2.4

### ISSUE THREAD

**Issue by cridmann** [dnvriend/akka-persistence-jdbc#16]
ScalikeJDBC's new version is not binary compatible with some of the methods used in this plugin:  https://github.com/scalikejdbc/scalikejdbc/issues/391

Bumping the dependency from 2.2.2 to 2.2.4 and rebuilding should resolve this issue.

Let me know if there are any problems with this - thanks!

**Comment by dnvriend** [comment]
Will be in release 1.1.1
