### ISSUE TITLE
Persistence with h2db is not working

### ISSUE THREAD

**Issue by siniconcur** [dnvriend/akka-persistence-jdbc#166]
WHEN I copy the the content of the configuration you given in example "h2-application.conf" into my application.conf, I get the error 
"slick.db - dataSource or dataSourceClassName or jdbcUrl is required.","logger_name":"com.zaxxer.hikari.HikariConfig"

persistence part of my application.conf looks like this.
persistence {
    journal {
      plugin = "jdbc-journal"
      auto-start-journals = ["jdbc-journal"]
    }
    snapshot-store {
      plugin = "jdbc-snapshot-store"
      auto-start-snapshot-stores = ["jdbc-snapshot-store"]
    }
  }

  slick {
    profile = "slick.jdbc.H2Profile$"
    db {
      url = "jdbc:h2:mem:test-database;DATABASE_TO_UPPER=false;"
      user = "root"
      password = "root"
      driver = "org.h2.Driver"
      connectionTestQuery = "SELECT 1"
    }
  }

    jdbc-journal {
    slick = ${slick}
    slick.db.numThreads = 20
    slick.db.maxConnections = 100
    slick.db.minConnections = 1
    slick.db.connectionTimeout = 1800000 // 30 minutes
    }

  jdbc-snapshot-store {
    slick = ${slick}
    slick.db.numThreads = 20
    slick.db.maxConnections = 100
    slick.db.minConnections = 1
    slick.db.connectionTimeout = 1800000 // 30 minutes
  }

**Comment by WellingR** [comment]
I see you also asked some questions in https://github.com/dnvriend/akka-persistence-jdbc/issues/116

As from the config you posted, these settings should be at the top level, not wrapped in `persistence {` block

**Comment by siniconcur** [comment]
Thanks a lot. That was the issue.
