### ISSUE TITLE
Database closing outside of Coordinated Shutdown

### ISSUE THREAD

**Issue by agnaldo4j** [dnvriend/akka-persistence-jdbc#171]
When my application down with SIGTERM, the database is closed immediately causing some errors.

To prevent this problem and have more control, I ask you if is possible to close the database inside of Coordinated Shutdown changing this code `sys.addShutdownHook(db.close())` in `akka.persistence.jdbc.query.JdbcReadJournal` line 72, to be inside of some phase of Coordinated Shutdown, maybe on “before-actor-system-terminate” or “actor-system-terminate”

Akka version: 2.5.9

**Comment by WellingR** [comment]
Good find. I was handling this as part of #151 but I am no longer actively working on this right now.

Previously this could not be implemented yet because coordinated shutdown is only part of akka 2.5. However we are no longer backporting all changes to the akka 2.4 branch anymore.
