### ISSUE TITLE
Correct thread/connection pool configuration

### ISSUE THREAD

**Issue by WellingR** [dnvriend/akka-persistence-jdbc#177]
Now that we have updated slick, the following warning appears in the log (during tests)

    WARN AsyncExecutor - Having maxConnection > maxThreads can result in deadlocks if transactions or database locks are used.

It seems that we need to change the default configuration, so that maxConnections and maxThreads are equal. 

See https://github.com/slick/slick/issues/1614#issuecomment-284730145

**Comment by renatocaval** [comment]
That's correct. We must have `minConnections == maxConnections == maxThreads`

This was a fix introduced in 3.2.2. 
https://github.com/slick/slick/pull/1855

**Comment by aturner-tvpage** [comment]
Which is weird, because I'm getting this error in slick 3.2.3

**Comment by mgilbertnz** [comment]
> Which is weird, because I'm getting this error in slick 3.2.3

For me the problem was with how I was getting the db instance when using this with Play.

Previously I was doing this....
```
class PostgresDatasourceImpl @Inject()()(implicit dbApi: DBApi)  {
  private lazy val source: DataSource = dbApi.databases().head.dataSource
  lazy val db: Database = Database.forDataSource(source, None)

  def runAction[R](action: DBIO[R]): Future[R] = db.run(action)
}
```

This needed to change to the following in order to pick up the correct config from the application.conf file:
```
class PostgresDatasourceImpl @Inject()()(protected val dbConfigProvider: DatabaseConfigProvider)
  extends HasDatabaseConfigProvider[JdbcProfile] {

  def runAction[R](action: DBIO[R]): Future[R] = dbConfig.db.run(action)
}
```
