### ISSUE TITLE
Add internal-ish API for in-place updates, for data migrations (e.g. encryption)

### ISSUE THREAD

**Issue by ktoso** [dnvriend/akka-persistence-jdbc#182]
Hi there,
We're looking to extend the JDBC plugin with a maybe surprising capability -- in place Update.
We'll make a small API in Akka itself shortly so that the plugin can be made to understand those extra operations. I have a WIP for the JDBC plugin already though and we worked on the Cassandra one as well.

The use case is for when someone decides when want to encrypt all their existing events, so they have to "replace them". Instead of telling people to do it manually, we will provide some mini infrastructure for such migrations in Akka -- the plugin will only need to understand the new "Update" operation, which it can handle in the pluginReceive.

Hope this makes sense :)

**Comment by renatocaval** [comment]
implemented on #183
