### ISSUE TITLE
currentPersistenceIds flatMapConcat currentEventsByPersistenceId issue with async combinators

### ISSUE THREAD

**Issue by skisel** [dnvriend/akka-persistence-jdbc#186]
Hi,

I'm fighting with very strange issue which I finally I was able to reproduce on the minimal case. I've persisted "fake" 20 persistenceIds 2 events each and now I'm struggling with JdbcReadJournal:

```
val migration = readJournal
    .currentPersistenceIds()
    .flatMapConcat { persistenceId =>
      readJournal
        .currentEventsByPersistenceId(persistenceId, 0, Long.MaxValue)
        .scanAsync(List[EventEnvelope]()) {
          case (acc, event) => Future.successful(List(event))
        }
    }
    .runForeach(event => println(event))
```

The following stream stops after emitting two events of single persistenceIds. If I remove scanAsync or change it to normal scan - it works as expected. 

I'm using default configuration of akka-persistence-jdbc. I tried it with Oracle and Postgres and can reproduce this issue with both databases. I upgraded all the latest libraries:
```
val akkaVersion = "2.5.12"
val slickVersion = "3.2.3"
val akkaPersistenceJdbcVersion = "3.3.0"
```

Let me know if I'm doing something wrong or I missed some information.

**Comment by skisel** [comment]
This one also fails with the same pattern:

```
    Source(List("712563be-be2d-4f2a-9b67-fa114e398967", "b75e0933-4881-4d47-89c5-03ed55131dd1"))
    .flatMapConcat { persistenceId =>
      readJournal
        .currentEventsByPersistenceId(persistenceId, 0, Long.MaxValue)
        .scanAsync(List[EventEnvelope]()) {
          case (acc, event) => Future.successful(List(event))
        }
    }
    .runForeach(event => println(event))
```

**Comment by renatocaval** [comment]
@skisel what is "working as expected" for you in this case?

I don't think this is related with the plugin but with your expectations on `scan` and `scanAsync`. 

From your code, I assume that you want to fetch all current IDs and then all current events and concatenate them in a single stream. And as far I can tell that's exactly what is happening, no? Once you fetch them all the stream stops and that is what is expected. Or am I missing something?

**Comment by skisel** [comment]
@renatocaval 

In general I think the problem is with syncAsync behavior which I referenced the ticket in akka/akka github. 

But let me explain what happens in this particular case. If we have two persistence ids like this:
"712563be-be2d-4f2a-9b67-fa114e398967", "b75e0933-4881-4d47-89c5-03ed55131dd1" and there are events persisted for each of them "1", "2" and "3". By running the scan with async or without I'm expecting the following output:
```
1
2
3
1
2
3
```

However, in scanAsync I get the following output and stream is never finished:
```
1
2
3
```

It looks to me scanAsync does close substream in this specific case.

**Comment by renatocaval** [comment]
Yeah, this is probably an issue with `scanAsync` instead. I will close the this issue if you don't mind. It's reported on the akka project which is the right place for it. 

Thanks
