### ISSUE TITLE
When using shared db's connections may be left open.

### ISSUE THREAD

**Issue by ignasi35** [dnvriend/akka-persistence-jdbc#192]
NOTE: `akka-persistence-jdbc` distinguishes between `dbs` and `shared-dbs`

* `akka-persistence-jdbc` uses `Actor#postStop` in `JdbcAsyncWriteJournal` and  `JdbsSnapshotStore`. There, `db.close` is invoked only if `db` is not shared. 
* `akka-persistence-jdbc` uses `CoordinatedShutdown#addTask` in `JdbcReadJournal`. `JdbcReadJournal` uses `coordinated-shutdown-phase`.
* `SlickExtension`'s `DbHolder` uses `CoordinatedShutdown#addTask` registering a task every time a new `db` is provided. `SlickExtension` uses `shared-db-coordinated-shutdown-phase`
* Both `coordinated-shutdown-phase` and `shared-db-coordinated-shutdown-phase` default to the phase `before-actor-system-terminate`.

`CoordinatedShutdown` only runs if invoked. By default `CoordinatedShutdown` terminates the `ActorSystem` and it is run on `SIGTERM`.

#### The problems:

1. Using the phase `before-actor-system-terminate` instead of the phase `actor-system-terminate` means actors are stopped _after_ `db.close` is run.
1. When an `ActorSystem` is _terminated_  using `ActorSystem.terminate` (as opposed to _shut down_ using `CoordinatedShutdown.run`), then tasks registered in `CoordinatedShutdown` are not run and `db`'s may be left open. There are scenarios where users simply use `ActorSystem.terminate` (e.g. tests). It is also possible users have their own JVM shutdown hook invoking `ActorSystem.terminate` in which case there's a race condition to see which JVM shutdown hook (userland v Akka's JVM shutdownhook) will invoke `db.close` first).

#### Proposals

1. Fixing this issue could be as simple as adding more docs: "in some scenarios only  `CoordinatedShutdown.run` will release all resources whihle `ActorSystem.terminate` won't" (needs nicer wording).
2. As a library, `akka-persistence-jdbc` may not rely on `CoordinatedShutdown` and instead trust only the actor's `postStop` and the ActorSystem's `registerOnTermination` features. Coordinated Shutdown will run `ActorSystem.terminate` in the last phases anyway.

**Comment by patriknw** [comment]
> As a library, akka-persistence-jdbc may not rely on CoordinatedShutdown and instead trust only the actor's postStop and the ActorSystem's registerOnTermination features. Coordinated Shutdown will run ActorSystem.terminate in the last phases anyway.

I think this is the right solution.

**Comment by renatocaval** [comment]
Let's go for solution 2 then. I was convinced that `ActorSystem.terminate` would trigger the `CoordinatedShutdown` and gracefully follow users instructions on how to stop everything. My bad.

**Comment by patriknw** [comment]
For historical reasons it’s the other way around.

**Comment by renatocaval** [comment]
Does it mean that one day `ActorSystem.terminate` will be deprecated in favor of `CoordinatedShutdown`?
