### ISSUE TITLE
InvalidClassException while replaying events

### ISSUE THREAD

**Issue by josh-s-g** [dnvriend/akka-persistence-jdbc#225]
Occasionally I'm unable to re-create an actor due to an InvalidClassException:
```
[ERROR] [akka://Foo/user/bea13f14-78e5-4b5a-8ebc-3b153b52ed42] Persistence failure when replaying events for persistenceId [bea13f14-78e5-4b5a-8ebc-3b153b52ed42]. Last known sequence number [0]
java.io.InvalidClassException: com.foo.bar.Action$Admin$; no valid constructor
```
I'm using a JSON serializer, and other persistence IDs with the same structure (including that Action Admin class) can have their events replayed just fine.

The only thing that I think is different between this persistence ID's events and any other (that can have their events replayed just fine) is that there are more events (>150) in the one that doesn't work.

Any thoughts on potential causes of this exception would be very helpful!

**Comment by WellingR** [comment]
If I google this error message then it really seems you are using java serialization.

Can you try to test while disabling java serialization as follows?

```
akka.actor.allow-java-serialization = off
```

You will probably get a different error (when writing the events) which will let you know that you probably have a misconfigured serializer

**Comment by josh-s-g** [comment]
Thanks @WellingR 
I'm using a customer JSON serializer, so adding
```
akka {
  actor {
    allow-java-serialization = off
  }
}
```
doesn't have any affect. My serializer code is pretty similar to the example in the Akka Persistence [docs](https://doc.akka.io/docs/akka/2.5/persistence-schema-evolution.html#configuring-payload-serializers) (instead using Circe to serialize to JSON):
```scala
class JsonSerializer extends SerializerWithStringManifest {

  val Utf8 = Charset.forName("UTF-8")
  val JsonManifest = "Json"
  def identifier = 1234567

  override def manifest(o: AnyRef): String = JsonManifest

  override def toBinary(obj: AnyRef): Array[Byte] = obj match {
    case e: Event =>
      e.asJson.noSpaces.getBytes(Utf8)
    case _ ⇒ throw new IllegalArgumentException(
      s"Unable to serialize to bytes, clazz was: ${obj.getClass}"
    )
  }

  override def fromBinary(bytes: Array[Byte], manifest: String): AnyRef = {
    manifest match {
      case JsonManifest =>
        val json = new String(bytes, Utf8)
        decode[OperationalEvent](json).right.get // Obviously .get isn't good practice here
      case _ => throw new NotSerializableException(
        s"Unable to deserialize from bytes, manifest was: $manifest! Bytes length: " + bytes.length
      )
    }
  }

}
```

Thanks

**Comment by WellingR** [comment]
@josh-s-g 

To be sure have been able to reproduce the issue on an event which as been written *after* you have disabled java serialization?

Does the exception you get have a stacktrace?

It would help if you can create a minimal example where you write and read an event, and reproduce this problem.

**Comment by josh-s-g** [comment]
Right, thanks for the pointers. I think I figured out that the java serialization was being used, but only for snapshots (not regular events). That's why only the persistence IDs with lots of events were showing this issue. I have 
```
akka {
  actor {
    allow-java-serialization = off
    serializers {
      Json = "com.foo.bar.JsonSerializer"
    }
    serialization-bindings {
      "com.foo.bar.events.Event" = Json
    }
  }
}
```

is there another configuration required to specify serialization for snapshots too?

**Comment by WellingR** [comment]
Yes, you do need to configure how your snapshot must be serialized, but this is similar to the serialization of regular events

```
    serialization-bindings {
      "com.foo.bar.events.Event" = Json
      "com.foo.bar.shapshots.Snapshot" = Json
    }
```

**Comment by josh-s-g** [comment]
Ok, great, thank you :+1:
