### ISSUE TITLE
Update to Slick 3.3.0

### ISSUE THREAD

**Issue by renatocaval** [dnvriend/akka-persistence-jdbc#228]
We are still using an olde version of Slick. 

Slick 3.3.0 has an important fix related with update of HikariCP and a deprecated (now removed) method.

See: https://github.com/slick/slick/pull/1932

This can potentially impact users of the plugin depending on how they create the Slick DB. 

See also: https://github.com/lagom/lagom/issues/1094

**Comment by WellingR** [comment]
The latest 3.5.0 release has been built using slick 3.3.0

See https://github.com/dnvriend/akka-persistence-jdbc/commit/f4672e3a624d2e2d82402fab54c159d3c4b6af41

**Comment by renatocaval** [comment]
I was checking it, but I think I was looking on the wrong branch. Sorry for the confusion.

Closing it.
