### ISSUE TITLE
duplicate key exceptions

### ISSUE THREAD

**Issue by prettynatty** [dnvriend/akka-persistence-jdbc#25]
Sometimes I see lots of exceptions came from akka-persistence-jdbc:

```
 ERROR s.StatementExecutor$$anon$1    SQL execution failed (Reason: ERROR: duplicate key value violates unique constraint "akka_snapshot_pkey"
  Detail: Key (persistence_id, sequence_nr)=(/user/sharding/GroupProcessorCoordinator/singleton/coordinator, 1880) already exists.):

   INSERT INTO public.snapshot (persistence_id, sequence_nr, created, snapshot) VALUES ('/user/sharding/GroupProcessorCoordinator/singleton/coordinator', 1880, 1439705139409, 'BAAAAAEAAACs7QAFc3IANGFra2EuY29udHJpYi5wYXR0ZXJuLlNoYXJkQ29vcmRpbmF0b3IkSW50ZXJuYWwkU3RhdGUAAAAAAAAA... (2360)')

 ERROR s.StatementExecutor$$anon$1    SQL execution failed (Reason: ERROR: duplicate key value violates unique constraint "akka_snapshot_pkey"
  Detail: Key (persistence_id, sequence_nr)=(/user/sharding/GroupDialogCoordinator/singleton/coordinator, 129) already exists.):

   INSERT INTO public.snapshot (persistence_id, sequence_nr, created, snapshot) VALUES ('/user/sharding/GroupDialogCoordinator/singleton/coordinator', 129, 1439705139418, 'BAAAAAEAAACs7QAFc3IANGFra2EuY29udHJpYi5wYXR0ZXJuLlNoYXJkQ29vcmRpbmF0b3IkSW50ZXJuYWwkU3RhdGUAAAAAAAAA... (1652)')

 ERROR s.StatementExecutor$$anon$1    SQL execution failed (Reason: ERROR: duplicate key value violates unique constraint "akka_snapshot_pkey"
  Detail: Key (persistence_id, sequence_nr)=(/user/sharding/PrivateDialogCoordinator/singleton/coordinator, 94) already exists.):

   INSERT INTO public.snapshot (persistence_id, sequence_nr, created, snapshot) VALUES ('/user/sharding/PrivateDialogCoordinator/singleton/coordinator', 94, 1439705139448, 'BAAAAAEAAACs7QAFc3IANGFra2EuY29udHJpYi5wYXR0ZXJuLlNoYXJkQ29vcmRpbmF0b3IkSW50ZXJuYWwkU3RhdGUAAAAAAAAA... (1412)')

 ERROR s.StatementExecutor$$anon$1    SQL execution failed (Reason: ERROR: duplicate key value violates unique constraint "akka_snapshot_pkey"
  Detail: Key (persistence_id, sequence_nr)=(/user/sharding/SeqUpdatesManagerCoordinator/singleton/coordinator, 3614) already exists.):
```

After tons of such errors connection pool stucks:

```
java.util.concurrent.RejectedExecutionException: Task slick.backend.DatabaseComponent$DatabaseDef$$anon$2@e4aa79f rejected from java.util.concurrent.ThreadPoolExecutor@312aac97[Running, pool size = 20, active threads = 20, queued tasks = 997, completed tasks = 381983]
```

I use akka 2.3.12, akka-persistence-jdbc 1.1.7 and PostgreSQL 9.4.0.

**Comment by dnvriend** [comment]
Looks like you have the issue from #18 that revolves around akka cluster snapshotting. In regards to Postgres the akka-persistence-jdbc driver uses a 'poor mans upsert' that first tries to insert a record, and if fails, tries to update the record, which should be [this statement](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/snapshot/Statements.scala#L72). Maybe this one should be handled with a stored procedure?

**Comment by mwkohout** [comment]
Postgres supports upserts.

**Comment by dnvriend** [comment]
Thanks for the information, It is true that postgres supports upserts but its only supported from postgres [v9.5.0 and up](https://wiki.postgresql.org/wiki/UPSERT), this case runs on v9.4.0, but that should not be a problem. A stored procedure could solve this and solving the extra roundtrip and bypassing scalikejdbc's error detection. 

Thanks for Keep the ideas coming

**Comment by tavisca-asingla** [comment]
hi, @dnvriend , I am still getting these exception that p_key already exists. The link you shared above seems to be broken for custom insert query. I tried to reach out on lightbend, but I think the problem is uncommon. Did not receive any response till now. https://discuss.lightbend.com/t/error-while-saving-snapshot-persistence-id-sequence-number-already-exists/7389

**Comment by tavisca-asingla** [comment]
I checked for debug logs of slick and sql being generated looks fine.
```
Executing prepared update: HikariProxyPreparedStatement@1548472201 wrapping update "event"."snapshot" set "created"=?,"snapshot"=? where "persistence_id"=? and "sequence_number"=?; insert into "event"."snapshot" ("persistence_id","sequence_number","created","snapshot") select ?,?,?,? where not exists (select 1 from "event"."snapshot" where "persistence_id"=? and "sequence_number"=?)
```
I am not sure why I am getting errors in upsert opertion when there is already a not exists check in the query for insert. Upsert works fine for first two times and for the third time it fails on same sequence Number.

I get the following error in the end:

```
 Detail: Key (persistence_id, sequence_number)=(MEMBERSHIP-1208784a-b2bb-44cd-b5c6-9117b0a91968, 5) already exists.
```
