### ISSUE TITLE
Compatibility with Akka 2.4.0-xx

### ISSUE THREAD

**Issue by dnvriend** [dnvriend/akka-persistence-jdbc#26]
I am working on a rewrite of the plugin to support Akka 2.4.0-xx. The new API allows for some smarter queries to be made and I assume the plugin will have a better memory and performance profile, both are welcome :)

**Comment by dnvriend** [comment]
Hi,

I have just released v1.2.0-RC2. It is an initial release of the JDBC plugin that works with Akka 2.4.0-RC2 and, because no obvious refactorings have been made, will be fully compatible with the latest 1.1.8 release configuration, database schema and serialization method. 

Because akka-persistence has stabilized and there are really good strategies in the [akka 2.4.0 docs](http://doc.akka.io/docs/akka/2.4.0-RC2/scala.html) on how to handle eg. event versioning and such, chances are that the plugin will be under construction for a bit, but along the way a migration guide will be setup on how to go from version to version and how to handle the new strategies.

Stay tuned and have fun!

**Comment by cleverdeveloper** [comment]
Is there a plan to support PersistenceQuery API?
http://doc.akka.io/docs/akka/snapshot/scala/persistence-query.html

**Comment by dnvriend** [comment]
I'm afraid that there are no plans. But if you have some free time to spare, please contribute and create a pull request :)

**Comment by prettynatty** [comment]
Perhaps it would be much easier to do it with slick as it can produce stream results.

**Comment by cleverdeveloper** [comment]
There is an example on how such query could be implemented in Akka documentation: http://doc.akka.io/docs/akka/snapshot/scala/persistence-query.html#Query_plugins
