### ISSUE TITLE
Adding a `test-query` configuration parameter?

### ISSUE THREAD

**Issue by elkorn** [dnvriend/akka-persistence-jdbc#32]
Hi!

I'm using `akka-persistence-jdbc` with `postgres-9.1.901.jdbc4` (PostgreSQL 9.3.9, Ubuntu 14.04).

The problem I'm getting while trying to use Persistence Query with the read journal is `java.sql.SQLException: JDBC4 Connection.isValid() method not supported, connection test query must be configured`.

From http://engineering.covata.com/programming/2014/07/11/akka-persistence-sql/ and https://github.com/brettwooldridge/HikariCP#initialization I gather that I should set up an equivalent of `akka.persistence.sql.common.db-connection.connectionTestQuery = "SELECT 1"` for it to initialize properly.
Is there a way to set that here somewhere?

My `application.conf`:

```
akka {
  loglevel = DEBUG

  persistence {
    journal {
      plugin = "jdbc-journal"
    }

    snapshot-store {
      plugin = "jdbc-snapshot-store"
    }
  }
}


akka-persistence-jdbc {
  slick {
    driver = "slick.driver.PostgresDriver"
    db {
      host = "localhost"
      host = ${?POSTGRES_HOST}
      port = "5432"
      port = ${?POSTGRES_PORT}
      name = "postgres"

      url = "jdbc:postgresql://"${akka-persistence-jdbc.slick.db.host}":"${akka-persistence-jdbc.slick.db.port}"/"${akka-persistence-jdbc.slick.db.name}
      user = "postgres"
      password = "apass"
      driver = "org.postgresql.Driver"
      keepAliveConnection = on
      numThreads = 2
      queueSize = 100
    }
  }

  tables {
    journal {
      tableName = "journal"
      schemaName = ""
      columnNames {
        persistenceId = "persistence_id"
        sequenceNumber = "sequence_number"
        created = "created"
        tags = "tags"
        message = "message"
      }
    }

    deletedTo {
      tableName = "deleted_to"
      schemaName = ""
      columnNames = {
        persistenceId = "persistence_id"
        deletedTo = "deleted_to"
      }
    }

    snapshot {
      tableName = "snapshot"
      schemaName = ""
      columnNames {
        persistenceId = "persistence_id"
        sequenceNumber = "sequence_number"
        created = "created"
        snapshot = "snapshot"
      }
    }
  }

  query {
    separator = ","
  }
}
```

I'm aware that there is a 90% probability that I am doing something wrong and I would appreciate having pointed out what that might be.

**Comment by dnvriend** [comment]
Hi. You can configure the following key:

`akka-persistence-jdbc.slick.db.connectionTestQuery="select 1"` 

Maybe you should disable the `keepAliveConnection`, ie set it to `off` or `false`.

**Comment by elkorn** [comment]
Thank you.
