### ISSUE TITLE
Can't resolve com.typesafe.slick#slick-extensions_2.11;3.1.0

### ISSUE THREAD

**Issue by divijan** [dnvriend/akka-persistence-jdbc#34]
This package, apparently, no longer is in Maven Central (http://search.maven.org/#search|ga|1|a%3A%22slick-extensions_2.11%22). The last mentioned version in slick documentation is 3.0.0

**Comment by dnvriend** [comment]
Apparently they aren't.. Please add the following to your build.sbt and let me know if it helps:

```scala
resolvers += "Typesafe Releases" at "http://repo.typesafe.com/typesafe/maven-releases/"
```

**Comment by divijan** [comment]
This helped, thanks. Will you update the README?

**Comment by dnvriend** [comment]
Yes I will change the README. Thanks for reporting!
