### ISSUE TITLE
akka-persistence-jdbc.tables.*.schemaName has no effect for postgres

### ISSUE THREAD

**Issue by divijan** [dnvriend/akka-persistence-jdbc#35]
I used the following script:

```
CREATE SCHEMA IF NOT EXISTS akka_persistence_jdbc;

DROP TABLE IF EXISTS akka_persistence_jdbc.journal;

CREATE TABLE IF NOT EXISTS akka_persistence_jdbc.journal (
  persistence_id VARCHAR(255) NOT NULL,
  sequence_number BIGINT NOT NULL,
  created BIGINT NOT NULL,
  tags VARCHAR(255) DEFAULT NULL,
  message BYTEA NOT NULL,
  PRIMARY KEY(persistence_id, sequence_number)
);

DROP TABLE IF EXISTS akka_persistence_jdbc.deleted_to;

CREATE TABLE IF NOT EXISTS akka_persistence_jdbc.deleted_to (
  persistence_id VARCHAR(255) NOT NULL,
  deleted_to BIGINT NOT NULL
);

DROP TABLE IF EXISTS akka_persistence_jdbc.snapshot;

CREATE TABLE IF NOT EXISTS akka_persistence_jdbc.snapshot (
  persistence_id VARCHAR(255) NOT NULL,
  sequence_number BIGINT NOT NULL,
  created BIGINT NOT NULL,
  snapshot BYTEA NOT NULL,
  PRIMARY KEY(persistence_id, sequence_number)
);
```
and specified ```tables.{journal/deletedTo/snapshot}.schemaName = "akka_persistence_jdbc".```
In the log I got ```org.postgresql.util.PSQLException: ERROR: relation "deleted_to" does not exist```.
So I decided to use the literal config from README, which worked, then I changed the schemaName in application.conf to "akka_persistence_jdbc" again and it continued to work. After that I deleted ```public.deleted_to``` table and got the abovementioned error again.

**Comment by dnvriend** [comment]
I have created a release v2.2.10 that fixes the issue. Due to a typo the schema name of the deleted_to and snapshot table were always None. The demo project now uses the custom `akka-persistence-jdbc` schema. You can review how to configure things to use a custom schema in the [demo project](https://github.com/dnvriend/demo-akka-persistence-jdbc). Thanks for reporting!
