### ISSUE TITLE
Offset in ReadJournal eventsByTag query is actually sequenceNr

### ISSUE THREAD

**Issue by wwwiiilll** [dnvriend/akka-persistence-jdbc#36]
The README mentions:
> You can retrieve a subset of all events by specifying offset, or use 0L to retrieve all events with a given tag. **The offset corresponds to an ordered sequence number for the specific tag.** Note that the corresponding offset of each event is provided in the EventEnvelope, which makes it possible to resume the stream at a later point from a given offset.

However what is actually used for the offset field of the EventEnvelope is the persistenceId's sequenceNr as it can be seen in the [ReadJournal implementation](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src%2Fmain%2Fscala%2Fakka%2Fpersistence%2Fjdbc%2Fquery%2Fjournal%2Fscaladsl%2FJdbcReadJournal.scala#L77):
```scala
  override def currentEventsByTag(tag: String, offset: Long): Source[EventEnvelope, NotUsed] =
    journalDao.eventsByTag(tag, offset)
      .via(serializationFacade.deserializeRepr)
      .mapAsync(1)(deserializedRepr ⇒ Future.fromTry(deserializedRepr))
      .map(repr ⇒ EventEnvelope(repr.sequenceNr, repr.persistenceId, repr.sequenceNr, repr.payload))
```

Looks like either the documentation or the implementation is wrong, or I may be missing something quite terribly here.

**Comment by dnvriend** [comment]
Thanks for creating the issue. You are absolutely correct, both the tests were missing, documentation partially correct and implementation plain wrong. All the query api results should be ordered by sequence number and where appropriate, the offset is inclusive so when the offset == 2, it should give event 2 and so on. Where a fromSeqNo and toSeqNo can be given, the behavior should be from 2 to 3 should return events 2 and 3. I have created the tests, changed the impl. and released `2.2.14` that should be available on JCenter any moment now.

**Comment by wwwiiilll** [comment]
Hmm, I don't think this would be the intended behavior either, at least for the `eventsByTag` query.
Here's an illustration of what I was be expecting from the README's description:

```
Actor1 with persistenceId = "actor-1"
Actor2 with persistenceId = "actor-2"
Actor3 with persistenceId = "actor-3"

Actor1 ! SomeMsg (tagged with "tag" by adapter)
Actor2 ! SomeMsg (tagged with "tag" by adapter)
Actor3 ! SomeMsg (tagged with "tag" by adapter)

// Expected in order from eventsByTag(0L, "tag")
EventEnvelope(1, "actor-1", 1, SomeMsg)
EventEnvelope(2, "actor-2", 1, SomeMsg)
EventEnvelope(3, "actor-3", 1, SomeMsg)

// Expected in order from eventsByTag(2L, "tag")
EventEnvelope(3, "actor-3", 1, SomeMsg)
```

Sorting by creation time did give the correct order and offsetting, but the sequenceNr as offset prevented us from saving it to resume the stream afterwards. We were seeing this instead:

```
// Received in order from eventsByTag(0L, "tag")
EventEnvelope(1, "actor-1", 1, SomeMsg)
EventEnvelope(1, "actor-2", 1, SomeMsg)
EventEnvelope(1, "actor-3", 1, SomeMsg)

// Received in order from eventsByTag(2L, "tag")
EventEnvelope(1, "actor-3", 1, SomeMsg)
```

I could try writing a test with that and send a pull request.

**Comment by dnvriend** [comment]
Ah, I (finally) understand the problem. Yes please alter the test and send a PR. I will look into the issue when I find the time.

**Comment by wwwiiilll** [comment]
I'm working on the byTag tests.

Also, I have a solution in mind that I'd like to try for that, but I'd have to return to the previous creation time based implementation for the byTag, would that be ok?

Finally, should the offsets start at 0 or 1?
The first event could be returned with offset 0 as in "if you ask again with this offset, you'll start here, so resume at offset + 1".
Or it could be returned with offset 1 as in "if you ask again with this offset you'll resume the stream right after this element".

**Comment by wwwiiilll** [comment]
Opened a PR with revised tests and the fixed implementation. Tests are all green on all DBs.

Also, I checked on the LevelDB query tests and the offset starts at 1, so for consistency I took the same approach.

**Comment by dnvriend** [comment]
Thanks for your contribution. Looks fine by me. I have merged and created a new release.
