### ISSUE TITLE
How to setup json converter

### ISSUE THREAD

**Issue by vtajzich** [dnvriend/akka-persistence-jdbc#38]
Hi,

I tried to setup json converter 

```
akka-persistence-jdbc {
  
  jdbc-connection {
    journal-converter  = "akka.persistence.jdbc.serialization.journal.JsonJournalConverter"
    snapshot-converter = "akka.persistence.jdbc.serialization.journal.JsonJournalConverter"
  }

  slick {
    driver = "slick.driver.PostgresDriver"
    db {
      host = "docker"
      port = "5432"
      name = "name"

      url = "jdbc:postgresql://"${akka-persistence-jdbc.slick.db.host}":"${akka-persistence-jdbc.slick.db.port}"/"${akka-persistence-jdbc.slick.db.name}
      user = "name"
      password = "pass"
      driver = "org.postgresql.Driver"
      keepAliveConnection = on
      numThreads = 1
      queueSize = 1000
    }
  }
}
```

I also tried to move to root, no changed.

however it's being serialized to bytes still. Where should I put the configuration?

thanks.

**Comment by dnvriend** [comment]
You should register the serializer in the path 'akka.actor.serializers' and then bind the class to the serializer by registering the FQCN to the name of the serializer in the path 'akka.actor.serialization-bindings'. Note however that, while the output of the serializer is JSON, the output of the serializer is a byte array and will be stored in the database as a byte-array. Please take a look at the configuration of the [demo project](https://github.com/dnvriend/demo-akka-persistence-jdbc/blob/master/src/main/resources/person-application.conf) that serializes domain objects using Google's Protocol Buffer.

**Comment by vtajzich** [comment]
thanks
