### ISSUE TITLE
Provide a way to shut-down connections explicitly

### ISSUE THREAD

**Issue by ktoso** [dnvriend/akka-persistence-jdbc#41]
When running a simple app like:

```scala
import akka.actor.{ActorSystem, Props}
import akka.persistence.{Persistence, PersistentActor}

object Application extends App {
  val system = ActorSystem()

  system.actorOf(Props(new PersistentActor {
    override def persistenceId: String = "the-guy"

    override def receiveRecover: Receive = {
      case x => println ("recover  : " + x + ", seqNr: " + lastSequenceNr)
    }

    override def receiveCommand: Receive = {
      case c => persist(c) { it => println("persisted: " + it + ", seqNr: " + lastSequenceNr) }
    }
  })) ! "hello world"
}
```

a number of  times after each other (default configuration, postgresql), connections seem to linger around and it's relatively simple to get:

```
[ERROR] [04/12/2016 12:08:30.612] [default-akka.actor.default-dispatcher-3] [akka://default/user/$a] Persistence failure when replaying events for persistenceId [the-guy]. Last known sequence number [0]
java.sql.SQLTimeoutException: Timeout after 1004ms of waiting for a connection.
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
	at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
	at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12)
	at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
	at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
	at slick.jdbc.JdbcBackend$BaseSession.startInTransaction(JdbcBackend.scala:437)
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:41)
	at slick.driver.JdbcActionComponent$StartTransaction$.run(JdbcActionComponent.scala:38)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:237)
	at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:427)
```
Would be good to provide a way to close connections cleanly once ActorSystem terminates (you can register actions to run when this happens)

**Comment by dnvriend** [comment]
Hi, I will look into the issue.

**Comment by dnvriend** [comment]
Did you explicitly terminate the ActorSystem? When I execute the code above verbatim it doesn't close the ActorSystem and any connections will remain open. But when I terminate the ActorSystem no connections are there to the database. I changed the code a bit:

```scala
import akka.actor.Status.Success
import akka.actor.{ ActorSystem, Props }
import akka.persistence.PersistentActor
import com.typesafe.config.ConfigFactory
import akka.pattern.ask
import akka.persistence.jdbc.extension.SlickDatabase
import akka.util.Timeout

import scala.concurrent.Await
import scala.concurrent.duration._

object Application extends App {
  implicit val timeout = Timeout(1.second)
  val configName = "default-application.conf"
  lazy val configuration = ConfigFactory.load(configName)
  val system = ActorSystem("app", configuration)

  val f = system.actorOf(Props(new PersistentActor {
    override def persistenceId: String = "the-guy"

    override def receiveRecover: Receive = {
      case x ⇒ println("recover  : " + x + ", seqNr: " + lastSequenceNr)
    }

    override def receiveCommand: Receive = {
      case c ⇒
        persist(c) { it ⇒ println("persisted: " + it + ", seqNr: " + lastSequenceNr) }
        sender() ! Success("Hello")
    }
  })) ? "hello world"

  //system.registerOnTermination(SlickDatabase(system).close)
  Await.ready(system.terminate(), 5.seconds)
  println("Terminated")
}
```

Please ignore the `system.registerOnTermination(SlickDatabase(system).close)` for now, I have a 2.2.17-SNAPSHOT that exposes Slick's Database `shutdown` and `close` methods just for testing.

**Comment by ktoso** [comment]
Yeah I'm pretty sure I had system.terminate (as I was using it in the repl and quitting the app (usual `readLine + system.terminate` at the end of it). Perhaps I messed up something hm...

**Comment by dnvriend** [comment]
I have released v2.2.17 that should address this issue. You should still explicitly terminate the ActorSystem though. It is also possible to explicitly terminate the HikariCP pool by calling `akka.persistence.jdbc.extension.SlickDatabase(system).close()`. Let me know if it works :)

**Comment by ktoso** [comment]
Very cool, I'll have a look!

**Comment by tavisca-asingla** [comment]
@dnvriend , in our application the open connections are not getting closed. Should I explicitly close those connections on termination of actor system by calling system.registerOnTermination(SlickDatabase(system).close)?

The number of  connections rises even if the actor system is not shut down. 

Current version is
implementation "com.github.dnvriend:akka-persistence-jdbc_$scalaCompactVersion:3.5.3"

We have nearly 709 idle connections in our test environments.
I am new to akka, and to pooling concept so not able to turn around the stones.

**Comment by ihostage** [comment]
Hello @tavisca-asingla,   

[Discuss forums](https://discuss.lightbend.com/) would be a better place to discuss this. Github issues are for reporting bugs and feature requests, not for general discussion and getting help.

Best.
