### ISSUE TITLE
Make it possible to have multiple instances of the plugin (configured differently)

### ISSUE THREAD

**Issue by ktoso** [dnvriend/akka-persistence-jdbc#42]
Currently the way config is obtained does not make use of the fallback and scoping mechanisms of Akka Persistence plugin configuration and makes it impossible to have 2 instances of the plugin, but configured differently (which I may want to do if I want to store sharding data in one table, but all other data in another)

**Comment by ktoso** [comment]
I'll attempt to solve this, however it may end up being not backwards compatible.

For more info see: doc.akka.io/docs/akka/current/scala/persistence.html#Multiple_persistence_plugin_configurations

**Comment by brycechesternewman** [comment]
👍 This is a very useful feature for us.

**Comment by dnvriend** [comment]
@ktoso I will fix it with the next release
