### ISSUE TITLE
Pluggable serialization proxy

### ISSUE THREAD

**Issue by acjay** [dnvriend/akka-persistence-jdbc#43]
This is probably on your radar already, but in my great quest for JSON serialization (which I think I'm abandoning) I looked into using the brand new `varchar` stuff. While it looks like this does indeed decouple things at the storage layer from the choice of database-level representation, it seems that all the plumbing up until that point still expects a byte stream. So somehow, `PersistentRepr` must still be serialized to a byte array. Even if that serialization is really UTF-8 encoded JSON as raw bytes, this seems to not quite be ideal, compared to letting the data be converted just once from in-memory representation to `String`.

Especially since I'm in the process of going the Protobuf route instead, this may be a request I don't actually need. But just for the sake of ticketing it, I thought I'd write it up.

In case it's helpful, my situation is that I'm using Akka Persistence to back up a RESTful API, so there are already JSON converters defined for all my types. While I realize protobuf will have much higher performance, the bandwidth to and from the persistent store isn't expected to be a bottleneck for a very long time, if ever. So the ability to only maintain one serialization layer, to not have to learn Protobuf, and to be able to directly inspect the database was really desirable.

**Comment by dnvriend** [comment]
You are correct that akka serialization uses the `Array[Byte]` interface. The varchar extension will take that Array[Byte] and convert it to a String just before saving the record. If you don't need this feature please close the ticket.

**Comment by acjay** [comment]
My point is that there would be an unnecessary round trip conversion (or at least reinterpretation). So supposing [`trait SerializationProxy`](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/serialization/SerializationProxy.scala#L38-L41) were parametric in the representation it serializes to, it seems like the DAOs could be made to deal with other intermediate representations, like `String`. But just a suggestion, it doesn't sound like you're interested, so I'll close.
