### ISSUE TITLE
Unable to differentiate between persistence failures and serialization issues

### ISSUE THREAD

**Issue by gopalsaob** [dnvriend/akka-persistence-jdbc#51]
In our application we use proto serializer for serializing domain events. What we have observed is the plugin/akka persistence invokes onPersistFailure() instead of onPersistRejected() for serialization issues. I believe this is because of the following code in SerializationProxy.serializeAtomicWrite()
    if (xs.exists(_.isFailure)) xs.filter(_.isFailure).head.asInstanceOf[Try[Iterable[SerializationResult]]] // SI-8566

Is this something that can be fixed or do we have any alternative way to differentiate the two failures?
We are using version 2.2.19 of this plugin and version 2.4.4 of akka persistence

**Comment by gopalsaob** [comment]
I have created a pull request for this issue #52

**Comment by dnvriend** [comment]
Hi, thanks for your contribution! I'm kinda busy right now so contributions from the community is very much appreciated in helping the plugin getting better and better! I've merged the PR and will release it shortly. Thanks again!
