### ISSUE TITLE
Efficient querying of many persistence IDs

### ISSUE THREAD

**Issue by acjay** [dnvriend/akka-persistence-jdbc#55]
I'm trying to optimize the read side of a system where I'm expecting to have on the order of, say, 1000 journals active at any given time. I'd like to have <1s latency between the write and read side of my system. I've read the source a bit of the Persistence Query implementation here, and correct me if I'm wrong, but if I set the polling interval to 1s and I have 1000 `eventsByPersistenceId` `Source`s open, I'm going to be generating 1000 DB queries per second. This doesn't seem scalable.

Do I have this correct? If so, is there a better way to accomplish what I'm going for here?

**Comment by dnvriend** [comment]
Having 1000 queries running on the database doesn't seem a good idea. Maybe just create one query for all pids and broadcast the emitted pids to other actors?

**Comment by acjay** [comment]
Well that was kind of my idea -- each of those other actors would hold a `eventsByPersistenceId`. But it seems like each of those sources would poll. I don't think there's a `allEvents` query, but if there were, I could have each actor bootstrap itself with `currentEventsByPersistenceId` and then have one centralized actor with an `allEvents` distribute the rest. But that feels fragile to me.

It seems like what could be missing is a way to centralize the polling, somehow. Not sure how that would work.

My current plan is to use `DistributedPubSub` to publish updates and then have my read-side actors listen via that channel. But it would be nice to be able to stay within the Akka ecosystem. Perhaps this is just a limitation of how Akk Persistence Query is currently designed.

**Comment by dnvriend** [comment]
For you non-functional requirements, <1s poll and ~1000 current events by pid on a single database and a single read journal the JDBC read journal is not a good solution. You could however store some pids on one database, and other pids on another database by overriding the `journalPluginId` of your persistent actor. You can then launch multiple jdbc-journal and multiple jdbc-read-journals, each pointing to another database. Say 10 databases for 10 pids? This way you have distributed the load across a number of databases.

**Comment by dnvriend** [comment]
You can read about overriding the journal and snapshot plugin here: http://doc.akka.io/docs/akka/2.4.7/scala/persistence.html#Multiple_persistence_plugin_configurations

**Comment by dnvriend** [comment]
This way you can even use a mix of storage technologies like Cassandra, Leveldb, JDBC for some pids. There are a lot of options to scale.

**Comment by acjay** [comment]
Thanks for the advice. So the thing about my use case is immediacy is a strong desire, but event volume is quite low (at the very most 10 per second at bursts, and far lower normally). So the overwhelming majority of those polls would reveal nothing had changed. 

I think the `DistributedPubSub` route may be the way to go for me, for now. I'm going to close, since I think the limitation is more with the framework. I mostly just wanted to figure out whether there was an idiomatic way within Akka Persistence Query to approach my use case, but I think the answer is probably not.

**Comment by dnvriend** [comment]
The akka-persistence-query is still experimental and I am running into issues myself. There is currently no idiomatic approach. The only advice I have is, if you have Cassandra at your disposal, chances are a whole lot better that it will match your non-functional requirements, albeit I have never experimented with it under such a load. The jdbc plugin however could be used when you are a bit creative with your system architecture eg. using more databases to distribute the load.

**Comment by acjay** [comment]
I'm a believer in the concept of "unless you have some kind of crazy functional need, just use Postgres. Otherwise, probably still use Postgres." :)

My use case isn't too exotic. I think it could probably be a simple library around Akka Persistence. I just get nervous about adding complex unfamiliar components to my setup unless it's a perfect fit. I already bit off about as much as I can chew going down the Akka rabbit hole :)
