### ISSUE TITLE
Is migration from 2.2.x to 2.6.x possible?

### ISSUE THREAD

**Issue by mcveat** [dnvriend/akka-persistence-jdbc#62]
I have an existing journal in postgres created using 2.2.8 version and want to use the most recent version now. I've migrated code and database schema to reflect the changes but reading the journal silently fails, with my suspicion being deserialization of the message field. The same code and schema with empty journal works as expected, persists new events and properly reads them.

Is it possible to migrate that data to be compliant with the most recent version of the library? My intuition is that it should be possible to implement a DAO that can handle events in both formats but wanted to make sure it is possible first. I'd appreciate any tips and hints :)

**Comment by dnvriend** [comment]
Hi, that's a very good question. I have never upgraded a journal, so I wouldn't know what problems one would find and I am sorry I cannot be of more help on that subject. I can only assume that the migration went flawless; copying the message wasn't corruping the data and the code base used a data model that supports schema versioning eg. like protobuf; ie you didn't store Java serialized data and you didn't change the package names of the data model and so on. Also, you would think that the PersistentRepr from Akka 2.4.2 would be compatible with v2.4.8 so I don't think that is the problem. Without any more information its anyones guess what goes wrong. 

Schema evolution on journals most of the time only affect the payload, so a format should be chosen that supports it eg. protobuf. But in this case the table schema changed; the ordering column was introduced. 

I hope it helps you somehow..

**Comment by dnvriend** [comment]
I have created a small project that stores 10 strings to the journal with v2.2.8, alters the database schema by just adding the `ordering` and `deleted` columns and tries to read the events with v2.6.3, it seems to work with the disclaimer that it only reads Java serialized strings from the journal. It seems to work though... Maybe you could take a look I have put it [here](https://github.com/dnvriend/akka22to26).

**Comment by mcveat** [comment]
Thank you so much for your help! I've been serializing my events as single json string each, so I should be in the clear. I guess the issue with recovering from the journal lies somewhere else. Hopefully, I can find what it is with the example you've made. Thank you for that one too!

**Comment by mcveat** [comment]
For the record, this is the schema migration I've been using

```
ALTER TABLE journal ADD COLUMN ordering BIGSERIAL;
ALTER TABLE journal ADD COLUMN deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE journal DROP COLUMN created;
ALTER TABLE journal DROP CONSTRAINT journal_pkey;
ALTER TABLE journal ADD PRIMARY KEY (ordering, persistence_id, sequence_number);

CREATE INDEX journal_persistence_id_sequence_number_idx ON public.journal(persistence_id, sequence_number);

DROP TABLE deleted_to;
```

**Comment by dnvriend** [comment]
I agree using JSON you should be in the clear (phew :) 

To be forward/backward compatible I used the following statements, as you can see in the [alter-schema.sh](https://github.com/dnvriend/akka22to26/blob/master/alter-schema.sh) script:

```sql
alter table journal add column ordering BIGSERIAL;
alter table journal add column deleted BOOLEAN DEFAULT FALSE;
alter table journal alter column created drop not null;
alter table journal alter column created set default 0;
alter table journal add column created_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE journal DROP CONSTRAINT journal_pkey;
ALTER TABLE journal ADD PRIMARY KEY (ordering, persistence_id, sequence_number);
CREATE INDEX journal_persistence_id_sequence_number_idx ON public.journal(persistence_id, sequence_number);
```

When v2.2.8 is not important anymore, you can drop `deleted_to` and drop the `created` column. I found that having a `created_ts` column is very handy for cleaning up your journal as the database creates a timestamp for each insert of the row. I have removed the `created_ts` row from the default schema because its not necessary for the journal to work, but for cleanup work its necessary ie. using the journal as a log structure with eg. a retention policy, deleting all records older than x HOURS, DAYS, WEEKS..

**Comment by mcveat** [comment]
Over the weekend I've gathered some more observations about the problem. Still not solved but maybe these findings will get us closer to its source.

First thing I've noticed that the migration script I've used is not correct for larger journals (mine has 1500 events). Adding column of a type `BIGSERIAL` to existing data applies values retrieved from sequence in the order of how rows are stored on the disk and not in the order of original inserts. Thus better migration script in my opinion should look like

```
CREATE TABLE new_journal (
  ordering BIGSERIAL,
  persistence_id VARCHAR(255) NOT NULL,
  sequence_number BIGINT NOT NULL,
  deleted BOOLEAN DEFAULT FALSE,
  tags VARCHAR(255) DEFAULT NULL,
  message BYTEA NOT NULL,
  PRIMARY KEY(persistence_id, sequence_number)
);

INSERT INTO new_journal(persistence_id, sequence_number, tags, message)  
SELECT persistence_id, sequence_number, tags, message 
FROM journal 
ORDER BY created, sequence_number;

DROP TABLE journal CASCADE;

ALTER TABLE new_journal RENAME TO journal;
```

Then, I've narrowed down the problem to three journal reads I'm performing at the application start. All three are reading from the same journal and materialize the events into three different views. I am reading it according to the snippet in the `README`:

```
PersistenceQuery(system).readJournalFor[JdbcReadJournal](JdbcReadJournal.Identifier)
      .eventsByPersistenceId(persistenceId, 0, Long.MaxValue)
      .runWith(/* some sink specific to the view */)
```

Unfortunately only one of these calls receives the events from the journal and commenting out either two make the third work. It is quite likely connected to the number of the events in the journal, because if I left only 10 events there, all three reads behave as expected.

**Comment by dnvriend** [comment]
I have tuned by jdbc-read-journal as follows:

```scala
jdbc-read-journal {
  refresh-interval = "5s"
  max-buffer-size = "500"
  slick.db.numThreads = 1000
  slick.db.maxConnections = 10
  slick.db.minConnections = 1
  slick.db.initializationFailFast = false
}
```

I found the configuration above is good enough to build projections.

**Comment by mcveat** [comment]
That was the missing piece, thank you!

**Comment by acjay** [comment]
I may have missed something, but it would be good if this were documented in the readme. I ran into the same issue of being surprised by the upgrade breaking my application in staging.
