### ISSUE TITLE
Getting 'Table "journal" not found' error with H2

### ISSUE THREAD

**Issue by devidatta45** [dnvriend/akka-persistence-jdbc#64]
I am new to akka-persistence and am trying to use H2 database for persistence. I referred the README and added the application.conf file as mentioned. But I am getting the error  when I try to start the application. Do I need to create the tables explicitly ? I saw the h2-schema.sql file, but where to actually keep it in the project ?

```
org.h2.jdbc.JdbcSQLException: Table "journal" not found; SQL statement:
select "sequence_number" from "journal" where "persistence_id" = ? order by "sequence_number" desc limit 1 [42102-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
```

**Comment by dnvriend** [comment]
Hi, it is necessary to have a schema when running the akka-persistence-jdbc plugin on any database like for example H2. The h2-schema.sql is available on the classpath of the akka-persistence-jdbc jar file or can be downloaded from [github using this link](https://raw.githubusercontent.com/dnvriend/akka-persistence-jdbc/master/src/main/resources/schema/h2/h2-schema.sql) 

Depending on your use case, eg. if you just need a persistency driver for unit testing applications an even better approach is to use [akka-persistence-inmemory](https://github.com/dnvriend/akka-persistence-inmemory) that doesn't need a running database nor a schema.

**Comment by yadavan88** [comment]
So, do we need to create the table manually before using it ? This is not for testing. Due to some issues, we are unable to use leveldb in a small device. So, thouht of trying with h2 and use the persist to disk of h2(should not be inmemory).

**Comment by dnvriend** [comment]
The tables should be created before the akka-persistence-jdbc can persist data in it. Creating tables can be done manually using JDBC but I've read H2 can do that for you [on a new connection](http://www.h2database.com/html/features.html#execute_sql_on_connection). The [h2 DDL SQL script](https://raw.githubusercontent.com/dnvriend/akka-persistence-jdbc/master/src/main/resources/schema/h2/h2-schema.sql) should be altered, to __not__ drop the tables, so just remove the `DROP` statements.

**Comment by yadavan88** [comment]
Thank you for the response. I shall try that out.

**Comment by dnvriend** [comment]
@yadavan88 Is this still an issue? If not, could you please close it? Thanks!

**Comment by yadavan88** [comment]
This is not an issue now. @devidatta45 can you please close this request ?
