### ISSUE TITLE
Event adapters not applied on `eventsByTag`

### ISSUE THREAD

**Issue by jvmakine** [dnvriend/akka-persistence-jdbc#65]
Hi! I'm migrating our database from Cassandra to Postgres, and with that, our connector to `akka-persistence-jdbc`. The problem I am having is that it seems that, unlike with the Cassandra connector, the event adapters are not being called when reading tagged events from `JdbcReadJournal`. My configuration is as follows (omitting the slick configuration):

```
jdbc-journal {   
  slick = ${slick} 
  recovery-event-timeout = 60m  
  event-adapters {   
    adapter = "com.x.Adapter"   
  }    
  event-adapter-bindings {     
    "com.x.PersistedEvent" = adapter   
  }
 }  

jdbc-snapshot-store {   
  slick = ${slick} 
} 

 jdbc-read-journal {   
  refresh-interval = "100ms"   
  max-buffer-size = "500"   
  batch-size = "250"   
  slick = ${slick} 
}
```

The adapter is being called correctly when writing events, but not when reading them from `JdbcReadJournal`.

Am I misunderstanding something, missing something from my configuration, or are the event adapters not supported when reading from the `JdbcReadJournal` with `eventsByTag`?

I am using version `2.6.5-RC2`

**Comment by dnvriend** [comment]
Hi, your configuration looks correct. AFAIK, event adapters are only applicable for persistence actors, they are for mapping the application domain messages on the data domain messages and vice versa. When querying the journal directly, you get an event envelope and you'll have to handle the data model directly. I have tried to create an image how it works: 

![event-adapters](https://github.com/dnvriend/akka-serialization-test/raw/master/img/akka-persistence-event-adapters.png)

**Comment by jvmakine** [comment]
Thank you very much for the fast response and clarifying this. I'll refactor our code accordingly and close this issue.

**Comment by filosganga** [comment]
@dnvriend The fact that you receive an EventEnvelope does not interfere with the event adaptation. If the query does not adapt events, it is completely useless as many migration logics are inside the EventAdapters.

FYI, The  Cassandra plugin and LevelDb plugin, that re the official ones, run the adapters also during the query.

But of course the decision is up to you.

**Comment by dnvriend** [comment]
Hi, thanks for the heads-up. I'll take a look.

**Comment by cwei-bgl** [comment]
@dnvriend I wish to have event adapters working with persistence query as well. It looks ugly to have these adapters in ReadJournal process. Thanks.

**Comment by Alnaimi-** [comment]
@dnvriend Any updates on this?, thanks :)

**Comment by dnvriend** [comment]
@Alnaimi- no eta on this feature, but its on the backlog.
