### ISSUE TITLE
Reason for change from scalikejdbc to slick?

### ISSUE THREAD

**Issue by firehooper** [dnvriend/akka-persistence-jdbc#68]
Could you please explain the reasoning for switch from  scalikejdbc to slick earlier this year (searched, but could not find an explanation).

**Comment by dnvriend** [comment]
Hi, very simple really. Slick is backed by Lightbend, formerly Typesafe. Slick allows for a pure functional way to access the database. Writing queries is a breeze with Slick as the DSL integrates with Scala, allowing you to write database access code much like working with Scala collections we know and love. Also, Slick is a more popular database access library than ScalikeJDBC and more importantly, when working with the Lightbend Reactive Platform, Slick is supported by Lightbend. As of earlier this year the enterprise database drivers became Open Source which is great! I hope this answers you question.

**Comment by firehooper** [comment]
Thanks
