### ISSUE TITLE
Snapshots table defines three primary keys

### ISSUE THREAD

**Issue by jroper** [dnvriend/akka-persistence-jdbc#71]
The snapshots table defines three primary keys, which is illegal:

``` scala
  class Snapshot(_tableTag: Tag) extends Table[SnapshotRow](_tableTag, _schemaName = snapshotTableCfg.schemaName, _tableName = snapshotTableCfg.tableName) {
    def * = (persistenceId, sequenceNumber, created, snapshot) <> (SnapshotRow.tupled, SnapshotRow.unapply)

    val persistenceId: Rep[String] = column[String](snapshotTableCfg.columnNames.persistenceId, O.Length(255, varying = true), O.PrimaryKey)
    val sequenceNumber: Rep[Long] = column[Long](snapshotTableCfg.columnNames.sequenceNumber, O.PrimaryKey)
    val created: Rep[Long] = column[Long](snapshotTableCfg.columnNames.created)
    val snapshot: Rep[Array[Byte]] = column[Array[Byte]](snapshotTableCfg.columnNames.snapshot)
    val pk = primaryKey("snapshot_pk", (persistenceId, sequenceNumber))
  }
```

Essentially this is saying that the persistenceId column is the primary key, the sequenceNumber column is the primary key, and there is also a composite primary key of the two of them.  Here's an example schema that Slick will generate for this:

``` sql
create table "snapshot" (
  "persistence_id" VARCHAR(255) NOT NULL PRIMARY KEY,
  "sequence_number" BIGINT NOT NULL PRIMARY KEY,
  "created" BIGINT NOT NULL,
  "snapshot" BLOB NOT NULL
);
alter table "snapshot" add constraint "snapshot_pk" primary key("persistence_id","sequence_number");
```

No database will execute this successfully since there are three primary keys defined.  The `O.PrimaryKey` option should be removed from the column definitions.

**Comment by jroper** [comment]
PR to fix in #72.

**Comment by dnvriend** [comment]
Hi, this is true, but for the fact that this workaround is necessary to get the UPSERT functionality working with Slick see [Slick Issue #966 - Scala's Slick with multiple PK insertOrUpdate() throws exception ERROR: syntax error at end of input](https://github.com/slick/slick/issues/966), as it stands, we must wait for slick 3.2.0

**Comment by jroper** [comment]
Interesting.  Right now I have a work around that simply removes "PRIMARY KEY" from the DDL statement, so I'll keep that.

**Comment by dnvriend** [comment]
Does this workaround break the UPSERT workaround?

**Comment by jroper** [comment]
No, the work around is completely separate from Slick, it's just taking the raw DDL statement strings as returned by schema.createStatements and doing a String.replace on them before creating the tables.
