### ISSUE TITLE
ReadJournalDao is tied to ByteArrayDao

### ISSUE THREAD

**Issue by datalchemist** [dnvriend/akka-persistence-jdbc#76]
Hi,

I have some trouble to implement my own ReadJournal Dao. Indeed, this latter defines the method eventsByTag with a return type that references akka.persistence.jdbc.dao.bytea.journal.JournalTables.JournalRow....which is the byte-array-based default DAO implementation. 
Hence, it is not possible to implement my own version based on different row type.

From what I understood by searching through the code, this JournalRow value is used only to retrieve the "ordering" value of the journal row.

As a very ugly workaround, I can construct a fake bytea.JournalRow.
I was also thinking about forking JdbcReadJournal

**Comment by dnvriend** [comment]
Hi, I understand the question. I did't foresee this albeit obvious :) I will look into refactoring it to only expose the Ordering value.
