### ISSUE TITLE
Custom PersistentRepr serialization to the database

### ISSUE THREAD

**Issue by arminc** [dnvriend/akka-persistence-jdbc#8]
I am currently serializing PersistentRepr by using an custom serialization. Although it works I still have to save redundant data in my json to be able to reconstruct the PersistentRepr. A sample of the data is (persistence-id, sequence-number). 

How about making a custom serialization of the PersistentRepr in the driver (make it optional), that way no redundant data is stored and everybody can still write there own custom serialization for there own events instead of also for the PersistentRepr.

**Comment by dnvriend** [comment]
Its (still) on my backlog...

**Comment by dnvriend** [comment]
I've created an extension so you can serialize the PersistentRepr and Snapshot using your own custom serializer to the database. I've also made some assumptions about a JSON variant. Please look at v1.1.2 of the akka-persistence-jdbc plugin, v1.0.0 of the akka-persistence-serialization-json serializer and the akka-persistence-jdbc-play example applications on how to go about using it. Let me know what you think! Out of the box the akka-persistence-jdbc plugin still uses Base64.
