### ISSUE TITLE
published artifact includes schema folder

### ISSUE THREAD

**Issue by naferx** [dnvriend/akka-persistence-jdbc#80]
Hi @dnvriend 
Currently, the published artifact is including the schema folder with the SQL scripts.

**Comment by naferx** [comment]
![captura](https://cloud.githubusercontent.com/assets/11840846/19945389/e7966620-a10d-11e6-9fe3-5cb3025c29b3.PNG)

**Comment by dnvriend** [comment]
Thanks for the head up, removed in the next release.

**Comment by naferx** [comment]
Thanks to you for maintaining this useful project ; )
