### ISSUE TITLE
Support the new query APIs from Akka 2.4.12

### ISSUE THREAD

**Issue by johanandren** [dnvriend/akka-persistence-jdbc#81]
Akka 2.4.12 introduced a shared `akka.persistence.query.Offset` type to replace the previously used `long` offset and two new queries using that Offset type: `CurrentEventsByTagQuery2` and `EventsByTagQuery2` (the awkward naming is because we intend to remove the old interfaces in next major Akka version and replace with the new ones but cannot right away because of compatibility)

**Comment by dnvriend** [comment]
Should be available in [akka-persistence-jdbc v2.6.8](https://dnvriend.github.io/akka-persistence/jdbc.html#2-6-8-2016-11-03-)

**Comment by johanandren** [comment]
Ah, awesome, sorry, I should have checked before opening a ticket.
