### ISSUE TITLE
eventsByTag returns events for wrong tag

### ISSUE THREAD

**Issue by cap3fme** [dnvriend/akka-persistence-jdbc#82]
Hi everyone,

When looking for events with tag "User" with `currentEventsByTag`, this also returns events with tag "UserEmail". In my opinion only events with tag "User" should be returned. I currently experience the problem when using the default dao configuration and a postgres backend.

When searching for the cause of this problem I found that in `package akka.persistence.jdbc.dao.bytea.readjournal` in [`trait BaseByteArrayReadJournalDao`](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/dao/bytea/readjournal/ByteArrayReadJournalDao.scala) events are filtered by `s"%$tag%"`. Might this be a bug?

With kind regards,
Felix

**Comment by dnvriend** [comment]
Hi, this is not a bug, but it is true that the `byTag` query should be changed, so it is more inline with the Cassandra tags.

**Comment by WellingR** [comment]
I actually do consider this a bug. We use a like query, which could actually return tags which we actually did not want.

A workaround is to ensure that no tag names are substrings of other tags.

A solution could be implemented where the tags are parsed, and filtered in the resulting stream.
