### ISSUE TITLE
No freeable memory during bulk load operations using PostgreSQL plugin driver

### ISSUE THREAD

**Issue by Sukesh-Alluri** [dnvriend/akka-persistence-jdbc#83]
Hi,
We currently use akka-persistence-jdbc 2.2.24 with akka-persistence 2.4.7 versions in our persistence service which is based on event sourcing model with PostgreSQL 9.5.2 running on AWS with below specs:
```
Instance Class	db.r3.2xlarge
Storage Type	Provisioned IOPS (SSD)
IOPS	18000
Storage in gigabytes	6000 GB
Memory (GB)	61 GB
```
On a typical load basis, we used to see nearly ~31 GB of memory left, but on bulk operations what we've seen is it reaches <2 GB, prompting to usually fast running queries to run slower resulting in RecoveryTimeouts in the persistent actor and from there on CircuitBreakerOpenException etc.,

So, by inspecting what exactly getting stored in that shared buffer in PostgreSQL, we found it stores the persistence_id and max sequence_number of the snapshot for each seen persistence_id until auto vacuum starts doing it's job. Below is the query we identified causing this:
```
select "persistence_id", "sequence_number", "created", "snapshot" from "snapshot" where ("persistence_id" = $1) and ("sequence_number" = (select max(x2.x3) from (select "persistence_id" as x4, "sequence_number" as x3 from "snapshot" where "persistence_id" = $2 order by "sequence_number" desc) x2)) order by "sequence_number" desc;
```
So, is there any way we can get the query to flush the cache upon these bulk loads and somehow apply back pressure on incoming messages or do we need to just upgrade our PostgreSQL server to handle more load?

Thanks in advance

**Comment by dnvriend** [comment]
Thank you for your question but I really don't know how to answer this. My gut feeling says that you are ready for a more powerful database engine like Apache Cassandra in combination with [akka-persistence-cassandra] driver so you have a better way to handle the (varying) load.
