### ISSUE TITLE
Migrate to Slick 3.2.0-M1

### ISSUE THREAD

**Issue by joseblas** [dnvriend/akka-persistence-jdbc#84]
Hi there,

 would be nice to migrate to Slick 3.2.0-M1. This is the first release within formerly known Extensions.
 I am working on that, so I'd like to share it with you once it's done and the tests are ok.

**Comment by dnvriend** [comment]
Wow, that's great! Let me know your findings. I'm thinking about having multiple runtimes for the jdbc-plugin and slick could be one of them.

**Comment by joseblas** [comment]
I will create a fork with my code. 
I've never done a runtime before, if you could provide some doc/examples we can do it together.

**Comment by joseblas** [comment]
Hi,
 I've just committed a pull request with my changes. Now we can work with that you mentioned about multiple runtimes.

**Comment by dnvriend** [comment]
Thats great, I am kinda busy right now on a project, but I'll get back to you ASAP.

**Comment by joseblas** [comment]
That's ok. I am happy to help. 

Regards, Jose.

**Comment by dnvriend** [comment]
Thanks, I have taken your code and released a test version `2.6.12-3.2.0-M2`.
