### ISSUE TITLE
eventsByTag query should not include the event at the offset passed in

### ISSUE THREAD

**Issue by TimMoore** [dnvriend/akka-persistence-jdbc#89]
We're using `akka-persistence-jdbc` to implement a resumable stream of events.

The workflow is:

1. Get an event stream for some tag using `eventsByTag(tag, NoOffset)`
2. Process each event in turn, and transactionally store its offset in an offset store (another database table with a row per tag)
3. When resuming the stream, retrieve the last processed offset from the offset store, and provide it to `eventsByTag(tag, offset)`

Unfortunately, this doesn't work as expected, because `akka-persistence-jdbc` is including the event at that offset in the query results at the start of the stream: https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/query/dao/ReadJournalQueries.scala#L50

This means that the last-processed event gets processed a second time.

You can see some discussion about this at https://github.com/lagom/lagom/pull/363

We're currently working around this by incrementing the offset before resuming the stream, but we think that `akka-persistence-jdbc` isn't implementing this query as intended. The tricky thing about it is that changing it now would break anything that is already working around the current behavior (they would then skip an event) but what are your thoughts @dnvriend?

**Comment by dnvriend** [comment]
Hi,

The eventsByTag has been implemented some time ago and I have a custom 'ResumableQuery' that persist its offset and does the +1 operation on the next query. But I want to understand the issue. 

According to the [documentation](http://doc.akka.io/docs/akka/current/scala/persistence-query.html#EventsByTag_and_CurrentEventsByTag) the example shows the following:

```
// start another query, from the known offset
val furtherBlueThings = readJournal.eventsByTag("blue", offset = Sequence(10))
```
The sentence "from the known offset", without any hints whether its inclusive or not is interpreted as inclusive. So I would expect the following when the query is executed:

```
sequence 10 -> event for tag blue
sequence 11 -> event for tag blue
sequence 12 -> event for tag blue
and so on
```

Do I understand correctly that you interpret the above sentence as being exclusive? So you would expect the following events:

```
sequence 11 -> event for tag blue
sequence 12 -> event for tag blue
and so on
```

**Comment by TimMoore** [comment]
I agree that the documentation isn't clear, but I believe the intent is to exclude it. Your second example is what I expect. The documentation you quoted implies that `furtherBlueThings` would not overlap with `top10BlueThings`.

One thing I was hoping, with the new `Offset` type in Akka, is that clients could treat it opaquely: each event is paired with an offset, and you can past the last-processed offset back to the event by tag query to get a stream of unprocessed events, without having to know the specific representation of the offset. Unfortunately, that isn't possible currently because of the need to increment the sequence number.

**Comment by dnvriend** [comment]
I've done some [research](https://github.com/dnvriend/akka-persistence-query-test/blob/master/src/test/scala/com/github/dnvriend/query/EventsByTagTest2.scala) in my [experiment project for akka-persistence-query](https://github.com/dnvriend/akka-persistence-query-test) but it seems that both the inmemory, jdbc and leveldb journal treat the offset inclusive. Maybe I'm missing something.

**Comment by TimMoore** [comment]
Thanks for looking into it @dnvriend. I got confirmation from @patriknw that the LevelDB implementation was a mistake (fixed now). See https://github.com/akka/akka/issues/22145 and https://github.com/akka/akka/pull/22146

**Comment by dnvriend** [comment]
That is what I was missing :) I use the leveldb impl. as reference as there is no TCK for query. Thanks!

**Comment by rrodseth** [comment]
I've been tearing my hair out over this as well. Also added 1 to the offset persisted in the resumable projection actor.
I then reverted to offset+0 in order to get a unit test passing, resulting in duplicates again (after a restart of the app). Any chance the in-memory and jdbc versions treat this differently?

**Comment by TimMoore** [comment]
@rrodseth looks like in-memory was changed in 2.1.16.0 to exclude the passed offset: https://github.com/dnvriend/akka-persistence-inmemory#24160-2017-01-29

**Comment by rrodseth** [comment]
Thank you! That might explain a lot, except I'm back on 1.2.12 (old version scheme). I'll poke around some more and try different versions. Would love to avoid separate code for tests and actual.

**Comment by TJSomething** [comment]
The workaround that I used was to use `dropWhile` to drop envelopes that matched the initial offset passed. This is a no-op for queries that used the old behavior and fix queries that use the current behavior.
