### ISSUE TITLE
overriding POSTGRES_HOST doesn't work

### ISSUE THREAD

**Issue by nsitbon** [dnvriend/akka-persistence-jdbc#90]
Hi, setting the environment variable POSTGRES_HOST to modify the default postgres host "boot2docker" doesn't work forcing me to override the whole url.
Thx

**Comment by dnvriend** [comment]
Hi, for normal operations you should configure `application.conf` and set the values. The variable you name is used by [travis.ci](https://travis-ci.org/) to build the project.

**Comment by WellingR** [comment]
@nsitbon the `POSTGRES_HOST` variable is in our example config to be able to override it on travis.

Does your `application.conf` file include the following section?

```
slick {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    host = "boot2docker"
    host = ${?POSTGRES_HOST}
    url = "jdbc:postgresql://"${slick.db.host}":5432/docker?reWriteBatchedInserts=true"
    //  some other settings, not relevant for this issue
  }
}
```

If so, then you should be able to override the environment variable. However this will only work if the part `host = ${?POSTGRES_HOST}` is included in your `application.conf` file in the correct place.

**Comment by WellingR** [comment]
Closing this issue since the reporter asked no further questions after the response from dnvriend.
@nsitbon if you have any further questions, feel free to reopen this issue
