### ISSUE TITLE
Request: change artifact name or re-increase version

### ISSUE THREAD

**Issue by sarahgerweck** [dnvriend/akka-persistence-jdbc#92]
It seems that you recently reduced the version number of the latest version of this library from 2.6.12 to 2.4.17.x. It's rather undesirable to have a version number decrease, because it now means that all your users will get notices for the foreseeable future saying that their version is out of date. I'm having to put a comment in our build-management system saying "2.4 is actually newer than 2.6 as of March 2017."

So I'm requesting that you either change the artifact name or that you increase the version number to restore its monotonicity: newer versions should have a higher version number. It's your project, but I'll lay out a few reasons why I think you and your users would benefit.

I'm guessing that this was done to align with Akka. If you really want to communicate the dependency on a particular version of Akka, I would suggest that a better approach is to have an artifact name like `akka-persistence-jdbc-akka2.4`. This "qualifier" approach is standard practice for things like JDBC drivers, Scala libraries, etc—and it's even codified into the Maven artifact standard.

Besides the fact that it leaves you with a version-number decrease, piggybacking on Akka's version numbers poses a couple of additional challenges.

The first is that it takes away your ability to use your own version number to communicate the scope of changes. It's dangerous for people to rely on this too much, but users do gain information from knowing whether they are upgrading from 2.6.12 to 2.6.13 or 3.0.0.

It also means that you're somewhat obliged to push a release of your software every time Akka does a point release, even though Akka maintains binary compatibility. It seems unlikely that there's any actual problem with using `akka-persistence-jdbc` 2.4.17.1 with `akka-persistence` 2.4.16, but it may create confusion if Akka 2.4.18 comes out and you're still on 2.4.17.x. 

I think it's worth noting that two projects in this space recently moved away from coupled version numbers for exactly this reason. Just in the last month or so Postgres decoupled the version of their database from the version of their JDBC drivers, for [basically these reasons](https://jdbc.postgresql.org/documentation/faq.html#version-change). Also, _Akka_ decided to stop synchronizing the version numbers of Akka HTTP and Akka Core [just a few months ago](http://akka.io/news/2016/11/22/akka-http-10.0.0-released.html) since they're not actually built together. (Akka HTTP went from version 2.4.12 to 10.0.0.)

Thanks for at least reading this and considering the request.

**Comment by dnvriend** [comment]
Hi Sarah. Thank you for the information and your suggestion. It gives food for thought and needs to sink in. I will park the issue for now, but will take it into consideration.

**Comment by sarahgerweck** [comment]
Thanks @dnvriend. 😄

**Comment by WellingR** [comment]
In the next release two versions will be released: 3.0.0 for akka 2.5, and 2.7.0 for akka 2.4

**Comment by WellingR** [comment]
Yesterday the versions 3.0.0 for akka 2.5, and 2.7.0 for akka 2.4 have been released. Therefore this issue has been resolved
