### ISSUE TITLE
ReadJournalDao directly wired to JournalRow

### ISSUE THREAD

**Issue by svenwiegand** [dnvriend/akka-persistence-jdbc#93]
At first: Thanks for that great persistence solution.

I like the possibility to provide custom DAO implementations. But there is one weak point in the `ReadJournalDao`: The `eventsByTag` is expected to return a `JournalRow`:

```scala
def eventsByTag(tag: String, offset: Long, max: Long): Source[Try[(PersistentRepr, Set[String], JournalRow)], NotUsed]
```

This makes it _nearly_ impossible to provide an own `ReadJournalDao` implementation based on something else but the `JournalRow`.

**Comment by WellingR** [comment]
Closing this now that #146 has been merged. The changes will be included in the next release.
