### ISSUE TITLE
Failed to persist event type [..] with sequence number [1]

### ISSUE THREAD

**Issue by tcak76** [dnvriend/akka-persistence-jdbc#98]
Hi,
I upgraded my project from
    Akka : 2.4.2 -> 2.4.17
    Slick : 3.1.1 -> 3.2.0
   akka-persistence-jdbc : 2.2.8 -> 2.4.17.1

Now I have problem, akka persistence persistAsync failed with **Failed to persist event type [..] with sequence number [1]** after 10 sec. I check that snapshot queries ran but persist not occurred. 

Do you have any idea about my issue?  Which layer akka or slick or persistence jdbc  or configuration layer is related with my issue? 

Now I am working to solve it, If anyone who encountered this type of problem help me, I am very appriciate.

**Comment by dnvriend** [comment]
Hi, if you create a small test project that has the same problem then I could take a look at the problem. For now, please review all the configuration items and ensure they are configured correctly.

**Comment by tcak76** [comment]
Hi,

Thank you for your interest.  I tried to solve my problem all the day and now I can run akka persistence with my configuration. But it is not a solution. It ran when debuging.

I fork this project and add below lines for debuging to the BaseByteArrayJournalDao class and now persistence working well. 

 override def writeFlow: Flow[AtomicWrite, Try[Unit], NotUsed] = {
    Flow[AtomicWrite]
      **.map(s => {
        println(s"Message in writeflow ${s}")
        s
      })**
      .via(serializer.serializeFlow)
      .map(_.map(writeJournalRows))
      .via(futureExtractor)
  }

When remove these lines, persistence is not working :) .  It is strange. Any idea about this.

**Comment by dnvriend** [comment]
Hi, that is strange. The println will force some synchronization to occur with IO, but I couln't imagine why this would work. Maybe remove the println and then ask sbt to do a ;clean;compile ?

**Comment by dnvriend** [comment]
I've created a small test project called [akka-persistence-jdbc-test](https://github.com/dnvriend/akka-persistence-jdbc-test), It works and does eventing and snapshotting, maybe you can take a look and see what the difference are.

**Comment by WellingR** [comment]
Closing this issue since there has been no more response form the issue author
@tcak76 if this issue still occurs, feel free to reopen
